site_name: Schedula

repo_name: "2023-1-Schedula"
repo_url: "https://github.com/fga-eps-mds/2023-1-Schedula-Doc"

theme:
  name: material
  language: "pt"
  icon:
    logo: material/police-badge-outline
    repo: fontawesome/brands/github
  palette:
    primary: "red"
    accent: "red"
  font:
    text: "Montserrat"
    code: "sans-serif"

extra_css:
  - stylesheets/styles.css

nav:
  - In√≠cio: index.md

dev_addr: "0.0.0.0:8000"
